#!/bin/bash

. /etc/aisheeblog/scripts.conf


saoluudata ()
{
echo "Backup $dataname..."
mkdir -p /home/$mainsite/private_html/backup/$dataname
cd /home/$mainsite/private_html/backup/$dataname
mysqldump -u root -p$mariadbpass $dataname | gzip -9 > $dataname.sql.gz

echo "Backup successful!"
echo "Path file backup: /home/$mainsite/private_html/backup/$dataname/$dataname.sql.gz"
echo "Link download: http://$mainsite:$priport/backup/$dataname/$dataname.sql.gz"
}

printf "=========================================================================\n"
printf "                             Backup Data\n"
printf "=========================================================================\n"
printf "Backup data file !!!\n\n"
echo -n "Input the database name [ENTER]: " 
read dataname

if [ -f /var/lib/mysql/$dataname/db.opt ]; then
echo "Found $dataname"
if [ -f /home/$mainsite/private_html/backup/$dataname/$dataname.sql.gz ]; then
read -r -p "Found backup file is old, delete and create new backupackup ? [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
    	rm -rf /home/$mainsite/private_html/backup/$dataname
	
	backupdata
        ;;
    *)
        echo "Good bye....!"
        ;;
esac
else
	backupdata
fi

else
echo "Not found $dataname !"
echo "Good bye...!"
exit
fi
